using System;
using System.Collections.Generic;

namespace CelinesChat;

internal static class Loc
{
    private static bool german;

    private static readonly Dictionary<string, (string En, string De)> Strings = new()
    {
        ["Window.Settings"] = ("Settings", "Einstellungen"),
        ["Window.Preview"] = ("Message Preview", "Nachrichtenvorschau"),
        ["Channel.Label"] = ("Channel:", "Kanal:"),
        ["Channel.Say"] = ("Say", "Sagen"),
        ["Channel.Party"] = ("Party", "Gruppe"),
        ["Channel.Whisper"] = ("Whisper", "Fluestern"),
        ["Channel.WhisperWithTarget"] = ("Whisper: {0}", "Fluestern: {0}"),
        ["Channel.Yell"] = ("Yell", "Ruf"),
        ["Channel.Shout"] = ("Shout", "Schrei"),
        ["Channel.FreeCompany"] = ("Free Company", "Freie Gesellschaft"),
        ["Channel.Linkshell"] = ("Linkshell", "Linkshell"),
        ["Channel.CrossWorldLinkshell"] = ("Cross-world Linkshell", "CW-Linkshell"),
        ["Channel.Alliance"] = ("Alliance", "Allianz"),
        ["Channel.PvpTeam"] = ("PvP Team", "PvP-Team"),
        ["Channel.NoviceNetwork"] = ("Novice Network", "Adepten-Netzwerk"),
        ["ChannelGroup.Standard"] = ("Standard", "Standard"),
        ["ChannelGroup.Announcements"] = ("Announcements", "Ankuendigungen"),
        ["ChannelGroup.Battle"] = ("Battle", "Kampf"),
        ["Channel.StandardEmote"] = ("Standard Emotes", "Standard-Emotes"),
        ["Channel.CustomEmote"] = ("Custom Emotes", "Eigene Emotes"),
        ["Channel.Notice"] = ("Notice", "Hinweis"),
        ["Channel.NoticeTooltip"] = ("Server-wide notices, e.g. login campaign messages.", "Serverweite Hinweise, z.B. Meldungen zu Login-Kampagnen."),
        ["Channel.Urgent"] = ("Urgent (other plugins)", "Dringend (andere Plugins)"),
        ["Channel.UrgentTooltip"] = ("Messages other installed plugins post into chat - most plugin output uses this.", "Nachrichten, die andere installierte Plugins in den Chat schreiben - die meisten Plugin-Ausgaben laufen darueber."),
        ["Channel.Debug"] = ("Debug (most plugin messages)", "Debug (die meisten Plugin-Nachrichten)"),
        ["Channel.DebugTooltip"] = ("Despite the name, this is the default channel Dalamud uses for plugin messages that don't pick a specific one - most small utility plugins' notifications (e.g. a doorbell/login alert) show up here, not under \"Urgent\".", "Trotz des Namens ist das der Standard-Kanal, den Dalamud fuer Plugin-Nachrichten ohne eigene Kanalwahl nutzt - die meisten Benachrichtigungen kleiner Hilfsplugins (z.B. eine Tuerklingel/Login-Meldung) laufen hier, nicht ueber \"Dringend\"."),
        ["Channel.SystemMessage"] = ("System Messages", "Systemnachrichten"),
        ["Channel.SystemError"] = ("Error Messages", "Fehlermeldungen"),
        ["Channel.SystemErrorTooltip"] = ("Native game errors, e.g. \"Player not found\" after trying to /tell someone offline or misspelled.", "Native Spielfehler, z.B. \"Spieler nicht gefunden\" bei /tell an jemanden, der offline ist oder falsch geschrieben wurde."),
        ["Channel.GatheringSystemMessage"] = ("Gathering System Messages", "Sammel-Systemnachrichten"),
        ["Channel.Echo"] = ("Echo", "Echo"),
        ["Channel.NoviceNetworkAnnouncements"] = ("Novice Network Announcements", "Adepten-Netzwerk-Ankuendigungen"),
        ["Channel.FreeCompanyAnnouncement"] = ("Free Company Announcements", "Freie-Gesellschaft-Ankuendigungen"),
        ["Channel.FreeCompanyLoginLogout"] = ("Free Company Member Login Notifications", "FC-Mitglied An-/Abmeldungen"),
        ["Channel.PvpTeamAnnouncement"] = ("PvP Team Announcements", "PvP-Team-Ankuendigungen"),
        ["Channel.PvpTeamLoginLogout"] = ("PvP Team Member Login Notifications", "PvP-Team-Mitglied An-/Abmeldungen"),
        ["Channel.RetainerSale"] = ("Retainer Sale Notifications", "Gehilfen-Verkaufsbenachrichtigungen"),
        ["Channel.NpcDialogue"] = ("NPC Dialogue", "NPC-Dialog"),
        ["Channel.NpcDialogueAnnouncements"] = ("NPC Dialogue (Announcements)", "NPC-Dialog (Ankuendigungen)"),
        ["Channel.LootNotice"] = ("Loot Notices", "Beute-Hinweise"),
        ["Channel.Progress"] = ("Progression Messages", "Fortschrittsnachrichten"),
        ["Channel.LootRoll"] = ("Loot Messages", "Beute-Wuerfeln"),
        ["Channel.Crafting"] = ("Synthesis Messages", "Synthetisieren-Nachrichten"),
        ["Channel.Gathering"] = ("Gathering Messages", "Sammel-Nachrichten"),
        ["Channel.PeriodicRecruitmentNotification"] = ("Periodic Recruitment Notifications", "Regelmaessige Rekrutierungsmeldungen"),
        ["Channel.Sign"] = ("Sign Messages", "Zeichen-Nachrichten"),
        ["Channel.RandomNumber"] = ("Random Number Messages", "Zufallszahlen-Nachrichten"),
        ["Channel.Orchestrion"] = ("Orchestrion Track Messages", "Orchestrion-Titel-Nachrichten"),
        ["Channel.MessageBook"] = ("Message Book Alert", "Nachrichtenbuch-Hinweis"),
        ["Channel.Alarm"] = ("Alarm Notifications", "Alarm-Benachrichtigungen"),
        ["Channel.GlamourNotifications"] = ("Glamour Notifications", "Glamour-Benachrichtigungen"),
        ["Channel.Damage"] = ("Damage", "Schaden"),
        ["Channel.Miss"] = ("Failed Attacks", "Fehlgeschlagene Angriffe"),
        ["Channel.ActionUsed"] = ("Actions Used", "Verwendete Aktionen"),
        ["Channel.ItemUsed"] = ("Items Used", "Verwendete Items"),
        ["Channel.Healing"] = ("Healing", "Heilung"),
        ["Channel.GainBuff"] = ("Beneficial Effects Granted", "Verliehene positive Effekte"),
        ["Channel.LoseBuff"] = ("Beneficial Effects Lost", "Verlorene positive Effekte"),
        ["Channel.GainDebuff"] = ("Detrimental Effects Inflicted", "Zugefuegte negative Effekte"),
        ["Channel.LoseDebuff"] = ("Detrimental Effects Cured", "Geheilte negative Effekte"),
        ["Whisper.TargetLabel"] = ("Target (Name@World):", "Ziel (Name@Welt):"),
        ["Whisper.UseTarget"] = ("Use target", "Ziel uebernehmen"),
        ["Whisper.Suggestions"] = ("Suggestions", "Vorschlaege"),
        ["Whisper.SuggestionsParty"] = ("-- Party --", "-- Gruppe --"),
        ["Whisper.SuggestionsRecent"] = ("-- Recent --", "-- Zuletzt --"),
        ["Whisper.NoSuggestions"] = ("No suggestions available", "Keine Vorschlaege vorhanden"),
        ["Compose.PreviewHeader"] = ("Preview:", "Vorschau:"),
        ["Compose.MessageCount"] = ("{0} message(s)", "{0} Nachricht(en)"),
        ["Compose.OpenPreviewWindow"] = ("Open preview in its own window", "Vorschau in eigenem Fenster oeffnen"),
        ["Compose.CharCount"] = ("{0}/{1} characters", "{0}/{1} Zeichen"),
        ["Compose.Sending"] = ("Sending {0}/{1}...", "Sende {0}/{1}..."),
        ["Compose.Cancel"] = ("Cancel", "Abbrechen"),
        ["Compose.Copy"] = ("Copy", "Kopieren"),
        ["Compose.Clear"] = ("Clear this tab", "Diesen Tab leeren"),
        ["Compose.Settings"] = ("Settings", "Einstellungen"),
        ["Compose.WindowLock"] = ("Lock window position and size", "Fensterposition und -groesse fixieren"),
        ["Compose.WindowUnlock"] = ("Unlock window position and size", "Fensterposition und -groesse entsperren"),
        ["Compose.HideChat"] = ("Hide chat (Enter brings it back)", "Chat ausblenden (Enter holt ihn zurueck)"),
        ["Settings.ValidCommandColor"] = ("Valid command color", "Farbe fuer gueltige Befehle"),
        ["Settings.InvalidCommandColor"] = ("Invalid command color", "Farbe fuer ungueltige Befehle"),
        ["Compose.OpenLog"] = ("Chat log", "Mitlesen"),
        ["Compose.Changelog"] = ("Changelog", "Changelog"),
        ["Compose.WhisperTargetMissing"] = ("Please enter a whisper target.", "Bitte ein Fluester-Ziel eingeben."),
        ["Compose.EmptyText"] = ("Please enter some text.", "Bitte Text eingeben."),
        ["Compose.WrapEmote"] = ("* Emote *", "* Emote *"),
        ["Compose.WrapOoc"] = ("(( OOC ))", "(( OOC ))"),
        ["Compose.RpActionsTooltip"] = ("RP actions", "RP-Aktionen"),
        ["Compose.AutoTranslate"] = ("Auto-Translate (Tab)", "Auto-Übersetzung (Tab)"),
        ["Compose.AutoTranslateSearchHint"] = ("Search auto-translate...", "Auto-Übersetzung suchen..."),
        ["Compose.AutoTranslateNoResults"] = ("No matches.", "Keine Treffer."),
        ["Compose.AutoTranslateBack"] = ("< Back to categories", "< Zurück zu Kategorien"),
        ["Compose.InsertMapFlag"] = ("Insert current map flag", "Aktuelle Kartenmarkierung einfügen"),
        ["Compose.AutoTranslateLoading"] = ("Loading...", "Lade..."),
        ["Compose.AutoTranslateLoadError"] = ("Couldn't load auto-translate data:", "Auto-Übersetzungsdaten konnten nicht geladen werden:"),
        ["Compose.Snippets"] = ("Templates", "Vorlagen"),
        ["Compose.History"] = ("History", "Verlauf"),
        ["Compose.NoSnippets"] = ("No templates saved yet.", "Noch keine Vorlagen gespeichert."),
        ["Compose.SnippetSearchHint"] = ("Search templates...", "Vorlagen suchen..."),
        ["Compose.RemoveSnippet"] = ("Remove", "Entfernen"),
        ["Compose.SnippetNameLabel"] = ("Name", "Name"),
        ["Compose.SaveSnippet"] = ("Save as template", "Als Vorlage speichern"),
        ["Compose.NoHistory"] = ("No messages sent yet.", "Noch keine Nachrichten gesendet."),
        ["ChatLog.ClickToWhisper"] = ("Right-click or Ctrl+Click to whisper", "Rechtsklick oder Strg+Klick zum Fluestern"),
        ["ChatLog.WhisperAction"] = ("Whisper", "Fluestern"),
        ["ChatLog.TargetAction"] = ("Target", "Ziel setzen"),
        ["ChatLog.InvitePartyAction"] = ("Invite to Party", "In Gruppe einladen"),
        ["ChatLog.AdventurerPlateAction"] = ("View Adventurer Plate", "Abenteurerkarte anzeigen"),
        ["ChatLog.BlockFunctionsMenu"] = ("Block Functions", "Blockierfunktionen"),
        ["ChatLog.AddToBlacklistAction"] = ("Add to Blacklist", "Zur Blockliste hinzufuegen"),
        ["ChatLog.AddToMuteListAction"] = ("Add to Mute List", "Zur Stummliste hinzufuegen"),
        ["ChatLog.AddToMuteListUnavailable"] = ("Not available yet for this message - the game hasn't reported this sender's account ID yet.", "Fuer diese Nachricht noch nicht verfuegbar - das Spiel hat die Account-ID dieses Absenders noch nicht gemeldet."),
        ["ChatLog.InviteNoviceNetworkAction"] = ("Invite to Novice Network", "In das Adepten-Netzwerk einladen"),
        ["ChatLog.ReplyInModeAction"] = ("Reply in Selected Chat Mode", "In diesem Kanal antworten"),
        ["ChatLog.SearchButtonTooltip"] = ("Search (right-click)", "Suchen (Rechtsklick)"),
        ["ChatLog.CopyMessage"] = ("Copy to clipboard", "In die Zwischenablage kopieren"),
        ["ChatLog.OpenFolder"] = ("Open logs folder", "Log-Ordner oeffnen"),
        ["ChatLog.LoadHistory"] = ("Load history", "Verlauf laden"),
        ["ChatLog.NoHistoryFiles"] = ("No log files found.", "Keine Log-Dateien gefunden."),
        ["ChatLog.HistorySearchHint"] = ("Search date (e.g. 2026-07)...", "Datum suchen (z.B. 2026-07)..."),
        ["ChatLog.BackToLive"] = ("Back to live", "Zurueck zu Live"),
        ["ChatLog.SearchHint"] = ("Search text or sender...", "Text oder Absender suchen..."),
        ["ChatLog.You"] = ("You", "Du"),
        ["ChatLog.ClearTabConfirm"] = ("Clear \"{0}\"? This only hides its messages from this tab, other tabs keep seeing them.", "\"{0}\" leeren? Das blendet die Nachrichten nur in diesem Tab aus, andere Tabs sehen sie weiterhin."),
        ["ChatLog.ClearTabConfirmYes"] = ("Clear", "Leeren"),
        ["ChatLog.ClearTabConfirmCancel"] = ("Cancel", "Abbrechen"),
        ["Whisper.ActiveIndicator"] = ("Whispering with {0}", "Fluestert mit {0}"),
        ["Settings.DefaultColor"] = ("Default text color", "Standard-Textfarbe"),
        ["Settings.EmoteColor"] = ("Emote color (*text*)", "Emote-Farbe (*Text*)"),
        ["Settings.EmotePreview"] = ("*sample text*", "*Beispieltext*"),
        ["Settings.OocColor"] = ("OOC color ((text))", "OOC-Farbe ((Text))"),
        ["Settings.OocPreview"] = ("((sample text))", "((Beispieltext))"),
        ["Settings.TimestampColor"] = ("Timestamp color", "Zeitstempel-Farbe"),
        ["Settings.MentionColor"] = ("Mention highlight color", "Erwaehnungs-Hervorhebungsfarbe"),
        ["Settings.MentionPreview"] = ("sample text", "Beispieltext"),
        ["Settings.SendAccentColor"] = ("Accent color (Send button, settings sidebar)", "Akzentfarbe (Senden-Button, Einstellungen-Seitenleiste)"),
        ["Settings.LogBackgroundOpacity"] = ("Chat log background opacity", "Hintergrund-Transparenz des Chatverlaufs"),
        ["Settings.MaxLength"] = ("Max. characters per message", "Max. Zeichen pro Nachricht"),
        ["Settings.Delay"] = ("Delay between messages (ms)", "Verzoegerung zwischen Nachrichten (ms)"),
        ["Settings.HotkeysHeader"] = ("Hotkeys:", "Hotkeys:"),
        ["Settings.SendOnEnter"] = ("Enter sends the message (Shift+Enter for a new line)", "Enter sendet die Nachricht (Shift+Enter fuer neue Zeile)"),
        ["Settings.SendOnEnterOff"] = ("Ctrl+Enter sends the message (Enter for a new line)", "Strg+Enter sendet die Nachricht (Enter fuer neue Zeile)"),
        ["Settings.FileLogHeader"] = ("Save to log file:", "In Log-Datei speichern:"),
        ["Settings.WindowOpacity"] = ("Window opacity (focused)", "Fenster-Transparenz (fokussiert)"),
        ["Settings.UnfocusedOpacity"] = ("Window opacity (unfocused)", "Fenster-Transparenz (nicht fokussiert)"),
        ["Settings.UnfocusedOpacityHint"] = ("Fades the compose and chat log windows when they're not focused, so they cover less of the screen while you're posing or playing an animation.", "Blendet Compose- und Mitlesefenster ab, wenn sie nicht fokussiert sind, damit sie weniger vom Bildschirm verdecken, waehrend du posierst oder eine Animation abspielst."),
        ["Settings.Reset"] = ("Reset to defaults", "Auf Standard zuruecksetzen"),
        ["Settings.WhisperDelayHint"] = ("Whispers always use at least {0} ms between messages, even if set lower above: /tell needs a server round-trip, and sending them too fast can make the game silently drop one.", "Fluesterbenachrichtigungen nutzen immer mindestens {0} ms zwischen Nachrichten, auch wenn oben weniger eingestellt ist: /tell braucht eine Server-Bestaetigung, und zu schnelles Senden kann dazu fuehren, dass das Spiel eine Nachricht stillschweigend verwirft."),
        ["Settings.SoundsHeader"] = ("Sounds:", "Sounds:"),
        ["Settings.PlaySounds"] = ("Play sound cues", "Sound-Hinweise abspielen"),
        ["Settings.WhisperSound"] = ("Play a sound when you receive a whisper", "Sound abspielen, wenn du angefluestert wirst"),
        ["Settings.MentionSound"] = ("Play a sound when your name is mentioned", "Sound abspielen, wenn dein Name erwaehnt wird"),
        ["Settings.MentionSoundHint"] = ("Off by default - in busy party/FC/shout chat this can trigger often enough to feel like noise rather than a useful alert.", "Standardmaessig aus - in belebtem Gruppen-/FC-/Ruf-Chat kann das oft genug ausloesen, um eher zu nerven als zu helfen."),
        ["Settings.SoundEffectFormat"] = ("SE %d", "SE %d"),
        ["Settings.SoundEffectTest"] = ("Test", "Testen"),
        ["Settings.VisibilityHeader"] = ("Visibility:", "Sichtbarkeit:"),
        ["Settings.VisibilityHint"] = ("The chat window hides itself outside actual gameplay (cutscenes, zone loading, character select) - pressing Enter still brings it back during a cutscene. These let it stay visible instead.", "Das Chatfenster blendet sich außerhalb des eigentlichen Spielgeschehens aus (Zwischensequenzen, Ladebildschirme, Charakterauswahl) - Enter holt es waehrend einer Zwischensequenz trotzdem zurueck. Hiermit bleibt es stattdessen sichtbar."),
        ["Settings.ShowDuringCutscenes"] = ("Show chat during cutscenes", "Chat waehrend Zwischensequenzen anzeigen"),
        ["Settings.ShowDuringLoadingScreens"] = ("Show chat during loading screens", "Chat waehrend Ladebildschirmen anzeigen"),
        ["Command.Help.Open"] = ("Opens the CelinesChat window.", "Oeffnet das CelinesChat-Fenster."),
        ["Command.Help.OpenLog"] = ("Opens the chat log window.", "Oeffnet das Mitlesefenster."),
        ["Log.SendError"] = ("Error sending message '{0}'.", "Fehler beim Senden der Nachricht '{0}'."),
        ["Settings.ColorsDescription"] = ("Choose the text color for each message type.", "Waehle die Textfarbe fuer jeden Nachrichtentyp."),
        ["Settings.LinkshellColorsHeader"] = ("Linkshell colors", "Linkshell-Farben"),
        ["Settings.CrossWorldLinkshellColorsHeader"] = ("Cross-world linkshell colors", "CW-Linkshell-Farben"),
        ["Settings.ColorsResetRow"] = ("Reset to default", "Auf Standard zuruecksetzen"),
        ["Tabs.DefaultAllName"] = ("General", "Allgemein"),
        ["Tabs.DefaultBattleLootName"] = ("Battle / Item", "Kampf / Item"),
        ["Tabs.Description"] = ("Create custom tabs and choose which message types show up in each one. Tabs are purely a display filter - they never change which channel your outgoing messages are sent to.", "Erstelle eigene Tabs und lege fest, welche Nachrichtentypen in jedem angezeigt werden. Tabs sind reine Anzeigefilter - sie aendern nie, an welchen Kanal ausgehende Nachrichten gesendet werden."),
        ["Tabs.AddButton"] = ("Add tab", "Tab hinzufuegen"),
        ["Tabs.NewTabDefaultName"] = ("New tab", "Neuer Tab"),
        ["Tabs.NameLabel"] = ("Name", "Name"),
        ["Tabs.RemoveButton"] = ("Remove tab", "Tab entfernen"),
        ["Tabs.CannotRemoveDefault"] = ("The default tab can't be removed.", "Der Standard-Tab kann nicht entfernt werden."),
        ["Tabs.PositionLocked"] = ("Lock position", "Position sperren"),
        ["Tabs.WhisperColorLabel"] = ("Color for this person", "Farbe fuer diese Person"),
        ["Tabs.MoveUp"] = ("Move up", "Nach oben"),
        ["Tabs.MoveDown"] = ("Move down", "Nach unten"),
        ["Tabs.SelectAllInGroup"] = ("Enable everything in this group", "Alles in dieser Gruppe aktivieren"),
        ["Tabs.DeselectAllInGroup"] = ("Disable everything in this group", "Alles in dieser Gruppe deaktivieren"),
        ["Tabs.MessageCountSuffix"] = ("message types", "Nachrichtentypen"),
        ["Tabs.SearchHint"] = ("Search message types...", "Nachrichtentypen suchen..."),
        ["Tabs.SearchTooltip"] = ("Also searches by keyword, not just the exact name - e.g. \"plugin\" finds where other plugins' messages show up.", "Sucht auch nach Schlagwoertern, nicht nur dem genauen Namen - z.B. findet \"plugin\" die Kategorie, in der Nachrichten anderer Plugins landen."),
        ["Nav.General"] = ("General", "Allgemein"),
        ["Nav.Colors"] = ("Colors", "Farben"),
        ["Nav.Tabs"] = ("Tabs", "Tabs"),
        ["Nav.Display"] = ("Display", "Anzeige"),
        ["Nav.Fonts"] = ("Fonts", "Schriftarten"),
        ["Fonts.Description"] = ("Only fonts bundled with Dalamud itself are offered here - they're guaranteed to load correctly, unlike an arbitrary system font.", "Hier werden nur Schriftarten angeboten, die mit Dalamud selbst mitgeliefert werden - diese laden garantiert korrekt, im Gegensatz zu einer beliebigen Systemschriftart."),
        ["Fonts.SizeLabel"] = ("Size", "Groesse"),
        ["Fonts.PreviewLabel"] = ("Preview:", "Vorschau:"),
        ["Fonts.PreviewText"] = ("The quick brown fox jumps over the lazy dog. 0123456789", "Der schnelle braune Fuchs springt ueber den faulen Hund. 0123456789"),
        ["Nav.FileLog"] = ("Log file", "Log-Datei"),
        ["Nav.Info"] = ("Info", "Info"),
        ["SecondaryChat.Title"] = ("Chat (2)", "Chat (2)"),
    };

    public static void SetLanguage(string uiLanguage)
    {
        german = string.Equals(uiLanguage, "de", StringComparison.OrdinalIgnoreCase);
    }

    public static string T(string key)
    {
        return Strings.TryGetValue(key, out var pair) ? (german ? pair.De : pair.En) : key;
    }

    public static string T(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }
}
