using System;
using System.Collections.Generic;

namespace CelinesToolkit;

internal static class Loc
{
    private static bool german;

    private static readonly Dictionary<string, (string En, string De)> Strings = new()
    {
        ["Delay.Label"] = ("Delay between commands (ms):", "Verzoegerung zwischen Befehlen (ms):"),
        ["Macro.New"] = ("+ New macro", "+ Neues Makro"),
        ["Macro.NewDefaultName"] = ("Macro {0}", "Makro {0}"),
        ["Macro.SelectHint"] = ("Select a macro on the left or create a new one.", "Waehle links ein Makro aus oder lege ein neues an."),
        ["Macro.Name"] = ("Name", "Name"),
        ["Macro.Run"] = ("Run", "Ausfuehren"),
        ["Macro.Delete"] = ("Delete macro", "Makro loeschen"),
        ["Macro.RunOnLogin"] = ("Run automatically on login", "Bei Login automatisch ausfuehren"),
        ["Macro.CommandsHeader"] = ("Commands (sent in order, e.g. /porch play 1):", "Befehle (werden der Reihe nach gesendet, z.B. /porch play 1):"),
        ["Macro.Up"] = ("Up", "Hoch"),
        ["Macro.Down"] = ("Down", "Runter"),
        ["Macro.Remove"] = ("Remove", "Entfernen"),
        ["Macro.AddCommand"] = ("+ Add command", "+ Befehl hinzufuegen"),
        ["Command.Help.Open"] = ("Opens the CelinesToolkit window.", "Oeffnet das CelinesToolkit-Fenster."),
        ["Command.Help.Run"] = ("Runs a saved macro: /ctrun <name>", "Fuehrt ein gespeichertes Makro aus: /ctrun <Name>"),
        ["Command.Help.GlamourerPreview"] = ("Opens the Glamourer preview window.", "Oeffnet das Glamourer-Vorschaufenster."),
        ["Log.NoNameGiven"] = ("No macro name given. Usage: /ctrun <name>", "Kein Makroname angegeben. Nutzung: /ctrun <Name>"),
        ["Log.MacroNotFound"] = ("Macro '{0}' was not found.", "Makro '{0}' wurde nicht gefunden."),
        ["Log.SendError"] = ("Error sending command '{0}'.", "Fehler beim Senden des Befehls '{0}'."),
        ["Nav.Overview"] = ("Overview", "Uebersicht"),
        ["Nav.CommandTool"] = ("Commandtool", "Commandtool"),
        ["Nav.Orchestrion"] = ("Orchestrion", "Orchestrion"),
        ["Overview.Title"] = ("Welcome to CelinesToolkit", "Willkommen bei CelinesToolkit"),
        ["Overview.Intro"] = ("A small collection of quality-of-life tools. Pick a category on the left to get started.", "Eine kleine Sammlung von Komfort-Werkzeugen. Waehle links eine Kategorie, um loszulegen."),
        ["Overview.FeatureCommandTool"] = ("Commandtool: build and run macros made of several chat commands", "Commandtool: Makros aus mehreren Chat-Befehlen erstellen und ausfuehren"),
        ["Overview.FeatureOrchestrion"] = ("Orchestrion: automatically mute Porch on login and zone change", "Orchestrion: Porch bei Login und Gebietswechsel automatisch stummschalten"),
        ["Orchestrion.RequiresPorch"] = ("Requires the main plugin by perchbird", "Benoetigt das Hauptplugin von perchbird"),
        ["Orchestrion.MuteCheckbox"] = ("Mute Orchestrion", "Mute Orchestrion"),
        ["Nav.PreviewManager"] = ("Preview Manager", "Preview Manager"),
        ["Nav.QuickBar"] = ("Quickbar", "Quickbar"),
        ["Overview.FeaturePreviewManager"] = ("Preview Manager: add preview images to Penumbra mods that are missing one", "Preview Manager: Vorschaubilder zu Penumbra-Mods hinzufuegen, denen eines fehlt"),
        ["Overview.FeatureQuickBar"] = ("Quickbar: a small always-on bar to run a saved macro with one click", "Quickbar: eine kleine, immer sichtbare Leiste, um ein gespeichertes Makro mit einem Klick auszufuehren"),
        ["QuickBar.Description"] = ("The quickbar is a small, always-visible bar with a dropdown to pick one of your saved macros and a Play button to run it instantly. It opens automatically on login once enabled here.", "Die Quickbar ist eine kleine, immer sichtbare Leiste mit einem Dropdown zur Auswahl eines gespeicherten Makros und einem Play-Button, um es sofort auszufuehren. Sie oeffnet sich nach dem Aktivieren automatisch beim Einloggen."),
        ["QuickBar.EnableCheckbox"] = ("Enable quickbar", "Quickbar aktivieren"),
        ["QuickBar.SelectHint"] = ("Select macro...", "Makro waehlen..."),
        ["QuickBar.FilterHint"] = ("Filter...", "Filter..."),
        ["QuickBar.NoMacros"] = ("No macros yet. Create one in Commandtool.", "Noch keine Makros. Lege eins im Commandtool an."),
        ["QuickBar.Play"] = ("Play", "Abspielen"),
        ["PreviewManager.Refresh"] = ("Refresh Mod List", "Modliste aktualisieren"),
        ["PreviewManager.OnlyMissing"] = ("Only show mods without a preview", "Nur Mods ohne Vorschaubild anzeigen"),
        ["PreviewManager.ShowInPenumbra"] = ("Also show preview image inside Penumbra's own mod settings", "Vorschaubild auch in Penumbras eigenem Mod-Fenster anzeigen"),
        ["PreviewManager.SearchHint"] = ("Search mod name...", "Mod-Name suchen..."),
        ["PreviewManager.TotalCount"] = ("{0} mods found", "{0} Mods gefunden"),
        ["PreviewManager.FilteredCount"] = ("{0} of {1} mods shown", "{0} von {1} Mods angezeigt"),
        ["PreviewManager.Enabled"] = ("enabled", "aktiv"),
        ["PreviewManager.Disabled"] = ("disabled", "inaktiv"),
        ["PreviewManager.EnabledUnknown"] = ("unknown", "unbekannt"),
        ["PreviewManager.PenumbraNotFound"] = ("Penumbra was not found. Please make sure it is installed and loaded.", "Penumbra wurde nicht gefunden. Bitte stelle sicher, dass es installiert und geladen ist."),
        ["PreviewManager.SelectHint"] = ("Select a mod on the left.", "Waehle links eine Mod aus."),
        ["PreviewManager.Author"] = ("Author: {0}", "Autor: {0}"),
        ["PreviewManager.Version"] = ("Version: {0}", "Version: {0}"),
        ["PreviewManager.NoPreview"] = ("No Preview Image Found", "Kein Vorschaubild gefunden"),
        ["PreviewManager.FromUrl"] = ("Grab Image from URL / XIVModArchive", "Bild von URL / XIVModArchive laden"),
        ["PreviewManager.GrabFromUrl"] = ("Grab & Scale Image", "Bild laden & skalieren"),
        ["PreviewManager.Loading"] = ("Loading...", "Laedt..."),
        ["PreviewManager.FromFile"] = ("Set Local Image File", "Lokale Bilddatei setzen"),
        ["PreviewManager.Browse"] = ("Browse...", "Durchsuchen..."),
        ["PreviewManager.SetLocalImage"] = ("Set Local Image", "Lokales Bild setzen"),
        ["PreviewManager.PasteFromClipboard"] = ("Paste Image from Clipboard", "Bild aus Zwischenablage einfuegen"),
        ["PreviewManager.Saved"] = ("Preview image saved to the mod folder.", "Vorschaubild im Mod-Ordner gespeichert."),
        ["PreviewManager.Error.Generic"] = ("Something went wrong while saving the image.", "Beim Speichern des Bildes ist etwas schiefgelaufen."),
        ["PreviewManager.Error.ClipboardEmpty"] = ("No image found in the clipboard.", "Kein Bild in der Zwischenablage gefunden."),
        ["PreviewManager.Error.NoImageFound"] = ("No image could be found on that page.", "Auf dieser Seite konnte kein Bild gefunden werden."),
        ["Nav.ShoppingList"] = ("Shopping List", "Einkaufsliste"),
        ["Overview.FeatureShoppingList"] = ("Shopping List: import a MakePlace list and see the cheapest total price", "Einkaufsliste: MakePlace-Liste importieren und den guenstigsten Gesamtpreis sehen"),
        ["ShoppingList.Description"] = ("Import a MakePlace shopping list (.list.txt) or a Teamcraft list export/clipboard paste to see the cheapest current market board price for every item, plus the grand total. Price data comes from the public Universalis API (universalis.app). Multiple imports are added together, so you can import several Teamcraft categories one after another.", "Importiere eine MakePlace-Einkaufsliste (.list.txt) oder einen Teamcraft-Listenexport/Zwischenablage-Inhalt, um fuer jedes Item den aktuell guenstigsten Marktpreis sowie die Gesamtsumme zu sehen. Die Preisdaten stammen von der oeffentlichen Universalis-API (universalis.app). Mehrere Importe werden zusammengezaehlt, so lassen sich mehrere Teamcraft-Kategorien nacheinander importieren."),
        ["ShoppingList.ImportButton"] = ("Import List...", "Liste importieren..."),
        ["ShoppingList.PasteButton"] = ("Paste from Clipboard", "Aus Zwischenablage einfuegen"),
        ["ShoppingList.ClearButton"] = ("Clear List", "Liste leeren"),
        ["ShoppingList.ClipboardSourceLabel"] = ("Clipboard", "Zwischenablage"),
        ["ShoppingList.Error.ClipboardEmpty"] = ("The clipboard is empty.", "Die Zwischenablage ist leer."),
        ["ShoppingList.Error.TimedOut"] = ("Timed out while fetching prices from Universalis. Please try again.", "Zeituberschreitung beim Abrufen der Preise von Universalis. Bitte erneut versuchen."),
        ["ShoppingList.NoListLoaded"] = ("No list imported yet.", "Noch keine Liste importiert."),
        ["ShoppingList.HomeWorldOnlyCheckbox"] = ("Only consider offers on my home world", "Nur Angebote auf meiner Heimatwelt beruecksichtigen"),
        ["ShoppingList.FetchPrices"] = ("Fetch Prices", "Preise abrufen"),
        ["ShoppingList.Fetching"] = ("Fetching prices...", "Preise werden abgerufen..."),
        ["ShoppingList.LookupLoading"] = ("Loading item database...", "Item-Datenbank wird geladen..."),
        ["ShoppingList.ColumnCategory"] = ("Category", "Kategorie"),
        ["ShoppingList.ColumnItem"] = ("Item", "Item"),
        ["ShoppingList.ColumnQuantity"] = ("Qty", "Menge"),
        ["ShoppingList.ColumnUnitPrice"] = ("Price/Unit", "Preis/Stueck"),
        ["ShoppingList.ColumnWorld"] = ("World (DC)", "Welt (DC)"),
        ["ShoppingList.ColumnTotal"] = ("Total", "Gesamt"),
        ["ShoppingList.StatusNotFound"] = ("Item not found", "Item nicht gefunden"),
        ["ShoppingList.StatusNotTradable"] = ("Not tradable", "Nicht handelbar"),
        ["ShoppingList.StatusNoListings"] = ("No market data", "Keine Marktdaten"),
        ["ShoppingList.StatusError"] = ("Error (home world unknown)", "Fehler (Heimatwelt unbekannt)"),
        ["ShoppingList.GrandTotal"] = ("Grand total: {0}", "Gesamtsumme: {0}"),
        ["ShoppingList.ItemCount"] = ("{0}x", "{0}x"),
        ["ShoppingList.WarningCount"] = ("{0} item(s) without a valid price", "{0} Item(s) ohne gueltigen Preis"),
        ["ShoppingList.LastUpdated"] = ("Last updated: {0}", "Zuletzt aktualisiert: {0}"),
        ["ShoppingList.SearchHint"] = ("Search item name...", "Item-Name suchen..."),
        ["Nav.HousingTracker"] = ("Housing Tracker", "Housing Tracker"),
        ["Overview.FeatureHousingTracker"] = ("Housing Tracker: see open housing plots on your home world, filterable by size, price and district", "Housing Tracker: offene Grundstuecke auf deiner Heimatwelt sehen, filterbar nach Groesse, Preis und Bezirk"),
        ["HousingTracker.Description"] = ("Shows every currently vacant housing plot on your home world, along with its lottery phase and ticket count. Data comes from the public, community-crowdsourced PaissaDB API (paissadb.zhu.codes) - it reflects the live state of each plot as it cycles through phases, since future lottery cycles aren't known until they actually open.", "Zeigt alle aktuell freien Grundstuecke auf deiner Heimatwelt inklusive Lotterie-Phase und Anzahl der Lose. Die Daten stammen von der oeffentlichen, community-basierten PaissaDB-API (paissadb.zhu.codes) - sie zeigen den aktuellen Stand jedes Grundstuecks in seinem Phasenzyklus, da zukuenftige Zyklen erst bei ihrem Start bekannt werden."),
        ["HousingTracker.FetchButton"] = ("Refresh", "Aktualisieren"),
        ["HousingTracker.Fetching"] = ("Fetching housing data...", "Housing-Daten werden abgerufen..."),
        ["HousingTracker.Error.NoHomeWorld"] = ("Could not determine your home world. Please make sure you are logged in.", "Heimatwelt konnte nicht ermittelt werden. Bitte stelle sicher, dass du eingeloggt bist."),
        ["HousingTracker.Error.FetchFailed"] = ("Failed to fetch housing data from PaissaDB. Please try again later.", "Housing-Daten konnten nicht von PaissaDB abgerufen werden. Bitte spaeter erneut versuchen."),
        ["HousingTracker.Error.TimedOut"] = ("Timed out while fetching housing data. Please try again.", "Zeituberschreitung beim Abrufen der Housing-Daten. Bitte erneut versuchen."),
        ["HousingTracker.NoDataYet"] = ("Click \"Refresh\" to load open housing plots for your home world.", "Klicke auf \"Aktualisieren\", um offene Grundstuecke deiner Heimatwelt zu laden."),
        ["HousingTracker.NoPlotsOpen"] = ("No open plots found on your home world right now.", "Aktuell keine offenen Grundstuecke auf deiner Heimatwelt gefunden."),
        ["HousingTracker.LastUpdated"] = ("Last updated: {0}", "Zuletzt aktualisiert: {0}"),
        ["HousingTracker.SizeFilterLabel"] = ("Size", "Groesse"),
        ["HousingTracker.DistrictFilterLabel"] = ("District", "Bezirk"),
        ["HousingTracker.FilterAll"] = ("All", "Alle"),
        ["HousingTracker.Size.Small"] = ("Small", "Klein"),
        ["HousingTracker.Size.Medium"] = ("Medium", "Mittel"),
        ["HousingTracker.Size.Large"] = ("Large", "Gross"),
        ["HousingTracker.ColumnDistrict"] = ("District", "Bezirk"),
        ["HousingTracker.ColumnWard"] = ("Ward", "Bezirksviertel"),
        ["HousingTracker.ColumnPlot"] = ("Plot", "Grundstueck"),
        ["HousingTracker.ColumnSize"] = ("Size", "Groesse"),
        ["HousingTracker.ColumnPrice"] = ("Price", "Preis"),
        ["HousingTracker.ColumnPhase"] = ("Phase", "Phase"),
        ["HousingTracker.ColumnTickets"] = ("Tickets", "Lose"),
        ["HousingTracker.ColumnPhaseUntil"] = ("Phase until", "Phase bis"),
        ["HousingTracker.Phase.EntryOpen"] = ("Entry open", "Entry open"),
        ["HousingTracker.Phase.Results"] = ("Result Phase", "Result Phase"),
        ["HousingTracker.Phase.Unavailable"] = ("Unavailable", "Nicht verfuegbar"),
        ["HousingTracker.Phase.DirectPurchase"] = ("Direct purchase", "Direktkauf"),
        ["HousingTracker.ResultCount"] = ("{0} of {1} plots shown", "{0} von {1} Grundstuecken angezeigt"),
        ["Nav.GlamourerPreview"] = ("Glamourer Preview", "Glamourer Preview"),
        ["Overview.FeatureGlamourerPreview"] = ("Glamourer Preview: browse your Glamourer designs with a preview image and apply them with one click", "Glamourer Preview: Glamourer-Designs mit Vorschaubild durchsuchen und mit einem Klick anwenden"),
        ["GlamourerPreview.Description"] = ("Opens a separate window that live-mirrors your Glamourer designs. Attach a preview image to each one and apply a design to yourself directly from there, without opening Glamourer itself.", "Oeffnet ein eigenes Fenster, das deine Glamourer-Designs live anzeigt. Hinterlege pro Design ein Vorschaubild und wende ein Design direkt von dort auf dich selbst an, ohne Glamourer selbst zu oeffnen."),
        ["GlamourerPreview.EnableCheckbox"] = ("Enable Glamourer preview window", "Glamourer-Vorschaufenster aktivieren"),
        ["GlamourerPreview.NotFound"] = ("Glamourer was not found. Please make sure it is installed and loaded.", "Glamourer wurde nicht gefunden. Bitte stelle sicher, dass es installiert und geladen ist."),
        ["GlamourerPreview.SelectHint"] = ("Select a design on the left.", "Waehle links ein Design aus."),
        ["GlamourerPreview.NoPreview"] = ("No Preview Image Found", "Kein Vorschaubild gefunden"),
        ["GlamourerPreview.Apply"] = ("Apply to myself", "Auf mich selbst anwenden"),
        ["GlamourerPreview.ApplySuccess"] = ("Design applied.", "Design angewendet."),
        ["GlamourerPreview.ApplyError"] = ("Could not apply design: {0}", "Design konnte nicht angewendet werden: {0}"),
        ["GlamourerPreview.ApplyHotkeyHint"] = ("Left click: apply everything. Ctrl+click: equipment only. Shift+click: appearance only.", "Linksklick: alles anwenden. Strg+Klick: nur Kleidung. Shift+Klick: nur Aussehen."),
        ["GlamourerPreview.ApplyToTarget"] = ("Apply to target", "Auf Ziel anwenden"),
        ["GlamourerPreview.OpenInGlamourer"] = ("Open in Glamourer", "In Glamourer oeffnen"),
        ["GlamourerPreview.Context.ApplySelfAll"] = ("Apply to myself (everything)", "Auf mich anwenden (alles)"),
        ["GlamourerPreview.Context.ApplySelfEquipment"] = ("Apply to myself (equipment only)", "Auf mich anwenden (nur Kleidung)"),
        ["GlamourerPreview.Context.ApplySelfCustomization"] = ("Apply to myself (appearance only)", "Auf mich anwenden (nur Aussehen)"),
        ["GlamourerPreview.Context.ApplyTargetAll"] = ("Apply to target (everything)", "Auf Ziel anwenden (alles)"),
        ["GlamourerPreview.Context.ApplyTargetEquipment"] = ("Apply to target (equipment only)", "Auf Ziel anwenden (nur Kleidung)"),
        ["GlamourerPreview.Context.ApplyTargetCustomization"] = ("Apply to target (appearance only)", "Auf Ziel anwenden (nur Aussehen)"),
        ["GlamourerPreview.Refresh"] = ("Refresh Designs", "Designs aktualisieren"),
        ["GlamourerPreview.SearchHint"] = ("Search design name...", "Design-Name suchen..."),
        ["GlamourerPreview.FromUrl"] = ("Grab Image from URL", "Bild von URL laden"),
        ["GlamourerPreview.Saved"] = ("Preview image saved.", "Vorschaubild gespeichert."),
        ["GlamourerPreview.TotalCount"] = ("{0} designs found", "{0} Designs gefunden"),
        ["GlamourerPreview.FilteredCount"] = ("{0} of {1} designs shown", "{0} von {1} Designs angezeigt"),
    };

    public static void SetLanguage(string uiLanguage)
    {
        german = string.Equals(uiLanguage, "de", StringComparison.OrdinalIgnoreCase);
    }

    public static string T(string key)
    {
        return Strings.TryGetValue(key, out var pair) ? (german ? pair.De : pair.En) : key;
    }

    public static string T(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }
}
